name: 🐛 Bug Report
description: Report a bug to help us improve Cadwyn-Go
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: search
    attributes:
      label: Search for existing issues
      description: Please search for existing issues before creating a new one.
      options:
        - label: I have searched for existing issues that might be related to this bug
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Set up Cadwyn with...
        2. Call the API endpoint...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Provide a minimal code example that reproduces the issue.
      render: go
      placeholder: |
        package main

        import (
            "github.com/gin-gonic/gin"
            "github.com/isaacchung/cadwyn-go/cadwyn"
        )

        func main() {
            // Your minimal reproducible example here
        }

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      render: yaml
      value: |
        - Go version: 
        - Cadwyn-Go version: 
        - Gin version: 
        - OS: 
        - Architecture: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Stack Trace
      description: If applicable, provide error logs or stack traces.
      render: text
      placeholder: Paste error logs or stack traces here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
