name: ✨ Feature Request
description: Suggest a new feature or improvement for Cadwyn-Go
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about what you'd like to see added to Cadwyn-Go.

  - type: checkboxes
    id: search
    attributes:
      label: Search for existing requests
      description: Please search for existing feature requests before creating a new one.
      options:
        - label: I have searched for existing feature requests that might be similar
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when... or I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Provide a specific use case or example of how this feature would be used.
      placeholder: |
        For example, when building an API that needs to...
        
        ```go
        // Example usage of the proposed feature
        ```

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes to the existing API?
      options:
        - label: This feature would require breaking changes
        - label: This feature can be implemented without breaking changes
        - label: I'm not sure about breaking changes

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my use case"
        - "Critical - Blocking my project"
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...
